### ISSUE TITLE
GeoLocation

### ISSUE THREAD

**Issue by TomMiksa** [alexrashed/tu-dpue-lab2-ss18#1]
Hi,

I have tried few different browsers and settings and I cannot get to the repository selection. I am getting notifications that your tool wants to check my location and independent on whether I agree or not, it says it uses Austria as default, but I cannot switch to the next view. 

Can you at least disable the geo location function and commit changes? Otherwise I am not able to click through the tool.

Best wishes
Tomasz Miksa

**Comment by alexrashed** [comment]
Hi!
We're investigating on the issue. Could you maybe give us an insight on the reference data you used in the previous step? As the mapping isn't trivial and the opendoar API is restricted by some bugs (as described in the readme) maybe there are no repos matching?
Thanks!

**Comment by TomMiksa** [comment]
I have uploaded PNG files for input and output and then clicked "continue". Then I got a pop-up that default location is selected and nothing else happens. I cannot switch to the next tab. If you have some test data for which it works, so that I could replicate your run, then it's enough for now.

**Comment by Tandagore** [comment]
The Opendoar-API throws an internal server error if the set limit is too high. In test runs the 30 (as limit) were working, but now it does not seem to work anymore. I've changed the limit of fetched repositories to 20 and it works on the local machine and in the local docker container. If there are still problems, please notify us.
Best Wishes, Georg Hagmann

**Comment by TomMiksa** [comment]
Thanks. It works!
